export const ROUTES = {
  home: '/',
  login: '/login',
  forgotPassword: '/forgotpassword',
  attendance: '/attendance',
  leave: '/leave',
  payroll: '/payroll',
  employee: '/employee',
  user: '/user',
  master: '/master',
  globalsetting: '/globalsetting',
  settings: '/settings',
  add: '/employee/create-or-update',
  update: '/employee/create-or-update/:id',
  changePassword: '/settings/change-password',
};
